### PR TITLE
Lz4 new

### PR DESCRIPTION
**Pull request by culotso**

### CODE REVIEW

**Comment by Tsunamical** [comment]
Render just reverted the change for clear_inode() in fs/f2fs/inode.c with the comment "I don't have all the required changes to use that function", do we have proper support for the function?

**Comment by culotso** [comment]
It is literally the exact same function, just renamed, and originating in the 'include/linux/fs.h'. There is a mix of end_writeback and clear_inode references in the fs/* stuff, most of it being end_writeback, but the f2fs stuff containing clear_inode, which wasn't compiling as the linux/fs.h include contained end_writeback, and not clear_inode. So I went whole-hog and updated the whole lot, so they all march to the same tune.

The hubbub originating from here, I believe: http://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/?id=dbd5768f87ff6fb0a4fe09c4d7b6c4a24de99430

**Comment by Tsunamical** [comment]
Oh, I didn't realize it renamed it, whoops. I guess that's what I get for no sleep. Anywho, it isn't really that necessary in my opinion.

**Comment by culotso** [comment]
Ah well, either way it works, end_writeback -> clear_inode, clear_inode -> end_writeback -- all just nomenclature, just that lone straggler was putting up a fight.

**Pull request closed without merging**
